const url = 'https://ubademy-ts-lorenzolgz.cloud.okteto.net/api';
const python = 'https://ubademy-chat-lorenzolgz.cloud.okteto.net';
export const chatEndpoint = python + '/chat';
export const deviceTokenEndpoint = python + '/users';
const loginEndPoint = url + '/users/login';
const registerEndPoint = url + '/users/register';
export const usersEndPoint = url + '/users';
export const coursesEndPoint = url + '/courses';
export const creatorsEndPoint = url + '/creators';
export const googleLoginEndpoint = url + '/auth/login';
export const underSubscription = coursesEndPoint + '/underSubscription';
export const categoriesEndpoint = coursesEndPoint + '/underCategory';
export {url, loginEndPoint, registerEndPoint};
